import React, { useState, useEffect } from 'react';
import { Printer, Download, Save, TrendingUp, AlertCircle } from 'lucide-react';
import { useAuth } from '../../contexts/AuthContext';
import axios from 'axios';
import { RadarChart, PolarGrid, PolarAngleAxis, PolarRadiusAxis, Radar, ResponsiveContainer } from 'recharts';

const BACKEND_URL = process.env.REACT_APP_BACKEND_URL;

const PlayerReportCard = () => {
  const { user } = useAuth();
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    if (user?.id) {
      fetchPlayerReport();
    }
  }, [user]);

  const fetchPlayerReport = async () => {
    try {
      setLoading(true);
      const token = localStorage.getItem('token');
      const headers = { Authorization: `Bearer ${token}` };

      // Try to fetch comprehensive roadmap report first
      try {
        const roadmapRes = await axios.get(`${BACKEND_URL}/api/reports/my-roadmap`, { headers });
        if (roadmapRes.data && roadmapRes.data.report_data) {
          const roadmap = roadmapRes.data.report_data;
          setReport({
            ...roadmap,
            isComprehensive: true
          });
          setLoading(false);
          return;
        }
      } catch (roadmapError) {
        console.log('No comprehensive roadmap found, using benchmark data');
      }

      // Fallback to benchmark data
      const benchmarksRes = await axios.get(`${BACKEND_URL}/api/auth/benchmarks`, { headers });
      
      if (benchmarksRes.data && benchmarksRes.data.length > 0) {
        const latestBenchmark = benchmarksRes.data[0];
        
        // Create report data
        const reportData = {
          playerName: user?.full_name || user?.username,
          age: user?.age || latestBenchmark.age,
          position: user?.position || latestBenchmark.position,
          date: new Date(latestBenchmark.benchmark_date).toLocaleDateString(),
          overallScore: Math.round(latestBenchmark.overall_score * 20),
          metrics: {
            physical: Math.round(latestBenchmark.physical_score * 20),
            technical: Math.round(latestBenchmark.technical_score * 20),
            tactical: Math.round(latestBenchmark.tactical_score * 20),
            psychological: Math.round(latestBenchmark.psychological_score * 20)
          },
          strengths: [
            latestBenchmark.physical_score >= 4 ? 'Physical Performance' : null,
            latestBenchmark.technical_score >= 4 ? 'Technical Skills' : null,
            latestBenchmark.tactical_score >= 4 ? 'Tactical Awareness' : null,
            latestBenchmark.psychological_score >= 4 ? 'Mental Strength' : null
          ].filter(Boolean),
          recommendations: [
            latestBenchmark.physical_score < 3 ? 'Focus on physical conditioning' : null,
            latestBenchmark.technical_score < 3 ? 'Improve ball control and passing' : null,
            latestBenchmark.tactical_score < 3 ? 'Work on tactical positioning' : null,
            latestBenchmark.psychological_score < 3 ? 'Develop mental resilience' : null
          ].filter(Boolean)
        };

        setReport(reportData);
      }
      setLoading(false);
    } catch (error) {
      console.error('Error fetching player report:', error);
      setLoading(false);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  const handleDownload = () => {
    if (!report) return;

    const reportText = `
PLAYER PERFORMANCE REPORT
========================

Player: ${report.playerName}
Age: ${report.age}
Position: ${report.position}
Date: ${report.date}

OVERALL SCORE: ${report.overallScore}/100

PERFORMANCE METRICS:
- Physical: ${report.metrics.physical}/100
- Technical: ${report.metrics.technical}/100
- Tactical: ${report.metrics.tactical}/100
- Psychological: ${report.metrics.psychological}/100

STRENGTHS:
${report.strengths.map(s => `- ${s}`).join('\n')}

RECOMMENDATIONS:
${report.recommendations.map(r => `- ${r}`).join('\n')}

Generated by Yo-Yo Elite Soccer Player AI Coach
    `;

    const blob = new Blob([reportText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `player-report-${report.playerName}-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleSave = async () => {
    try {
      setSaving(true);
      const token = localStorage.getItem('token');
      const headers = { Authorization: `Bearer ${token}` };

      await axios.post(`${BACKEND_URL}/api/auth/save-report`, {
        report_data: report,
        report_type: 'performance_snapshot'
      }, { headers });

      alert('Report saved successfully!');
      setSaving(false);
    } catch (error) {
      console.error('Error saving report:', error);
      alert('Failed to save report. Please try again.');
      setSaving(false);
    }
  };

  if (loading) {
    return (
      <div className="max-w-6xl mx-auto p-6">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-purple-600 mx-auto"></div>
      </div>
    );
  }

  if (!report) {
    return (
      <div className="max-w-6xl mx-auto p-6">
        <div className="bg-white rounded-2xl p-12 shadow-lg border-2 border-purple-200 text-center">
          <AlertCircle className="w-16 h-16 text-purple-600 mx-auto mb-4" />
          <h3 className="text-2xl font-bold text-gray-800 mb-2">No Report Available</h3>
          <p className="text-gray-600 mb-6">Complete an assessment to generate your player report.</p>
          <button className="px-6 py-3 bg-gradient-to-r from-purple-600 to-indigo-600 text-white rounded-xl font-semibold hover:from-purple-700 hover:to-indigo-700 transition">
            Take Assessment
          </button>
        </div>
      </div>
    );
  }

  const radarData = [
    { category: 'Physical', value: report.metrics.physical },
    { category: 'Technical', value: report.metrics.technical },
    { category: 'Tactical', value: report.metrics.tactical },
    { category: 'Psychological', value: report.metrics.psychological }
  ];

  return (
    <div className="max-w-6xl mx-auto p-6 space-y-6">
      {/* Header with Actions */}
      <div className="bg-gradient-to-r from-indigo-600 via-purple-600 to-pink-600 rounded-2xl p-6 text-white shadow-lg border-2 border-yellow-400">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-3xl font-bold mb-2">📊 Player Performance Report</h2>
            <p className="text-white/90">Current snapshot and recommendations</p>
          </div>
          <div className="flex gap-2">
            <button
              onClick={handlePrint}
              className="px-4 py-2 bg-white/20 hover:bg-white/30 rounded-lg transition flex items-center gap-2"
            >
              <Printer className="w-4 h-4" />
              <span className="hidden md:inline">Print</span>
            </button>
            <button
              onClick={handleDownload}
              className="px-4 py-2 bg-white/20 hover:bg-white/30 rounded-lg transition flex items-center gap-2"
            >
              <Download className="w-4 h-4" />
              <span className="hidden md:inline">Download</span>
            </button>
            <button
              onClick={handleSave}
              disabled={saving}
              className="px-4 py-2 bg-yellow-400 text-indigo-900 hover:bg-yellow-300 rounded-lg transition flex items-center gap-2 font-semibold disabled:opacity-50"
            >
              <Save className="w-4 h-4" />
              <span className="hidden md:inline">{saving ? 'Saving...' : 'Save'}</span>
            </button>
          </div>
        </div>
      </div>

      {/* Report Content */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Player Info & Score */}
        <div className="bg-white rounded-2xl p-6 shadow-lg border border-gray-200">
          <div className="text-center mb-6">
            <div className="w-24 h-24 bg-gradient-to-br from-yellow-400 to-orange-500 rounded-full mx-auto mb-4 flex items-center justify-center">
              <span className="text-4xl font-bold text-indigo-900">
                {report.overallScore}
              </span>
            </div>
            <h3 className="text-2xl font-bold text-gray-800 mb-1">{report.playerName}</h3>
            <p className="text-gray-600">Age: {report.age} | Position: {report.position}</p>
            <p className="text-sm text-gray-500 mt-2">Report Date: {report.date}</p>
          </div>

          <div className="grid grid-cols-2 gap-4 mt-6">
            <div className="bg-purple-50 rounded-xl p-4 text-center">
              <p className="text-sm text-purple-600 font-medium">Physical</p>
              <p className="text-2xl font-bold text-purple-900">{report.metrics.physical}</p>
            </div>
            <div className="bg-blue-50 rounded-xl p-4 text-center">
              <p className="text-sm text-blue-600 font-medium">Technical</p>
              <p className="text-2xl font-bold text-blue-900">{report.metrics.technical}</p>
            </div>
            <div className="bg-green-50 rounded-xl p-4 text-center">
              <p className="text-sm text-green-600 font-medium">Tactical</p>
              <p className="text-2xl font-bold text-green-900">{report.metrics.tactical}</p>
            </div>
            <div className="bg-orange-50 rounded-xl p-4 text-center">
              <p className="text-sm text-orange-600 font-medium">Mental</p>
              <p className="text-2xl font-bold text-orange-900">{report.metrics.psychological}</p>
            </div>
          </div>
        </div>

        {/* Radar Chart */}
        <div className="bg-white rounded-2xl p-6 shadow-lg border border-gray-200">
          <h3 className="text-xl font-bold text-gray-800 mb-4">Performance Profile</h3>
          <ResponsiveContainer width="100%" height={300}>
            <RadarChart data={radarData}>
              <PolarGrid stroke="#e5e7eb" />
              <PolarAngleAxis dataKey="category" />
              <PolarRadiusAxis domain={[0, 100]} />
              <Radar name="Performance" dataKey="value" stroke="#8b5cf6" fill="#8b5cf6" fillOpacity={0.6} />
            </RadarChart>
          </ResponsiveContainer>
        </div>
      </div>

      {/* Strengths & Recommendations */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Strengths */}
        <div className="bg-gradient-to-br from-green-50 to-emerald-50 rounded-2xl p-6 shadow-lg border-2 border-green-200">
          <div className="flex items-center gap-2 mb-4">
            <TrendingUp className="w-6 h-6 text-green-600" />
            <h3 className="text-xl font-bold text-gray-800">💪 Strengths</h3>
          </div>
          <ul className="space-y-2">
            {report.strengths.length > 0 ? (
              report.strengths.map((strength, idx) => (
                <li key={idx} className="flex items-center gap-2">
                  <span className="w-2 h-2 bg-green-600 rounded-full"></span>
                  <span className="text-gray-700">{strength}</span>
                </li>
              ))
            ) : (
              <li className="text-gray-600 italic">Keep working to identify your strengths</li>
            )}
          </ul>
        </div>

        {/* Recommendations */}
        <div className="bg-gradient-to-br from-yellow-50 to-orange-50 rounded-2xl p-6 shadow-lg border-2 border-yellow-200">
          <div className="flex items-center gap-2 mb-4">
            <AlertCircle className="w-6 h-6 text-orange-600" />
            <h3 className="text-xl font-bold text-gray-800">🎯 Focus Areas</h3>
          </div>
          <ul className="space-y-2">
            {report.recommendations.length > 0 ? (
              report.recommendations.map((rec, idx) => (
                <li key={idx} className="flex items-start gap-2">
                  <span className="text-orange-600 font-bold mt-1">{idx + 1}.</span>
                  <span className="text-gray-700">{rec}</span>
                </li>
              ))
            ) : (
              <li className="text-gray-600 italic">Excellent work! Keep maintaining your performance</li>
            )}
          </ul>
        </div>
      </div>

      {/* Comprehensive Roadmap Sections - Only if comprehensive report */}
      {report.isComprehensive && report.ai_analysis && (
        <>
          {/* AI Analysis Section */}
          <div className="bg-gradient-to-br from-blue-50 to-indigo-50 rounded-2xl p-6 shadow-lg border-2 border-blue-200">
            <h3 className="text-xl font-bold text-gray-800 mb-4">🤖 AI Performance Analysis</h3>
            <div className="bg-white rounded-xl p-4">
              <p className="text-gray-700 leading-relaxed whitespace-pre-wrap">{report.ai_analysis}</p>
            </div>
          </div>

          {/* Coach Recommendations Section */}
          {report.coach_recommendations && report.coach_recommendations.length > 0 && (
            <div className="bg-gradient-to-br from-purple-50 to-pink-50 rounded-2xl p-6 shadow-lg border-2 border-purple-200">
              <h3 className="text-xl font-bold text-gray-800 mb-4">👨‍🏫 Coach Recommendations</h3>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {report.coach_recommendations.map((rec, idx) => (
                  <div key={idx} className="bg-white rounded-xl p-4 shadow">
                    <div className="flex items-start gap-3">
                      <div className="w-8 h-8 bg-purple-600 text-white rounded-full flex items-center justify-center font-bold text-sm flex-shrink-0">
                        {idx + 1}
                      </div>
                      <p className="text-gray-700 text-sm">{rec.replace(/^\d+\.\s*/, '')}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Standards Comparison */}
          {report.standards_comparison && (
            <div className="bg-gradient-to-br from-orange-50 to-red-50 rounded-2xl p-6 shadow-lg border-2 border-orange-200">
              <h3 className="text-xl font-bold text-gray-800 mb-4">📏 Standards Comparison</h3>
              <div className="bg-white rounded-xl p-4">
                <p className="text-gray-700 leading-relaxed whitespace-pre-wrap">
                  {report.standards_comparison.analysis || JSON.stringify(report.standards_comparison, null, 2)}
                </p>
              </div>
            </div>
          )}

          {/* 12-Week Development Roadmap */}
          {report.development_roadmap && (
            <div className="bg-gradient-to-br from-teal-50 to-cyan-50 rounded-2xl p-6 shadow-lg border-2 border-teal-200">
              <h3 className="text-xl font-bold text-gray-800 mb-4">🗺️ 12-Week Development Roadmap</h3>
              <div className="space-y-4">
                {report.development_roadmap.phase_1 && (
                  <div className="bg-white rounded-xl p-4 shadow">
                    <h4 className="font-bold text-teal-700 mb-2">Phase 1: Weeks 1-4</h4>
                    <p className="text-gray-700">{report.development_roadmap.phase_1}</p>
                  </div>
                )}
                {report.development_roadmap.phase_2 && (
                  <div className="bg-white rounded-xl p-4 shadow">
                    <h4 className="font-bold text-teal-700 mb-2">Phase 2: Weeks 5-8</h4>
                    <p className="text-gray-700">{report.development_roadmap.phase_2}</p>
                  </div>
                )}
                {report.development_roadmap.phase_3 && (
                  <div className="bg-white rounded-xl p-4 shadow">
                    <h4 className="font-bold text-teal-700 mb-2">Phase 3: Weeks 9-12</h4>
                    <p className="text-gray-700">{report.development_roadmap.phase_3}</p>
                  </div>
                )}
              </div>
            </div>
          )}
        </>
      )}
    </div>
  );
};

export default PlayerReportCard;
