import React, { useState, useEffect } from 'react';
import { useAuth } from '../../contexts/AuthContext';
import { useLocation, useNavigate } from 'react-router-dom';
import axios from 'axios';
import { Printer, Download, Save, TrendingUp, Play, ArrowRight, CheckCircle } from 'lucide-react';
import { RadarChart, PolarGrid, PolarAngleAxis, PolarRadiusAxis, Radar, ResponsiveContainer, LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, Legend } from 'recharts';

const BACKEND_URL = process.env.REACT_APP_BACKEND_URL;

const ProfessionalAssessmentReport = () => {
  const { user } = useAuth();
  const location = useLocation();
  const navigate = useNavigate();
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(true);
  const [generatingProgram, setGeneratingProgram] = useState(false);
  const [programGenerated, setProgramGenerated] = useState(false);
  const [showProgramForm, setShowProgramForm] = useState(false);
  const [programParams, setProgramParams] = useState({
    training_days_per_week: 4,
    duration_weeks: 12,
    session_duration_minutes: 60,
    gender: user?.gender || 'male',
    has_injuries: false,
    injury_details: '',
    recovery_priority: 'moderate',
    availability: 'after_school',
    goals: '',
    equipment_available: 'full'
  });

  useEffect(() => {
    // Get assessment ID from URL params or location state
    const params = new URLSearchParams(location.search);
    const assessmentId = params.get('assessment_id') || location.state?.assessmentId;
    
    if (assessmentId) {
      fetchProfessionalReport(assessmentId);
    } else {
      console.error('No assessment ID provided');
      setLoading(false);
    }
  }, [location]);

  const fetchProfessionalReport = async (assessmentId) => {
    try {
      setLoading(true);
      const token = localStorage.getItem('token');
      const headers = { Authorization: `Bearer ${token}` };

      // Fetch comprehensive roadmap report
      const response = await axios.post(
        `${BACKEND_URL}/api/reports/generate-comprehensive-roadmap?assessment_id=${assessmentId}`,
        {},
        { headers }
      );

      if (response.data.success) {
        setReport(response.data.report_data);
      }
      
      setLoading(false);
    } catch (error) {
      console.error('Error fetching professional report:', error);
      setLoading(false);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  const handleDownload = () => {
    if (!report) return;

    const reportText = `
PROFESSIONAL SOCCER PLAYER ASSESSMENT REPORT
============================================

PLAYER INFORMATION:
Player Name: ${report.player_info.name}
Age: ${report.player_info.age}
Position: ${report.player_info.position}
Height: ${report.player_info.height}
Weight: ${report.player_info.weight}
Dominant Foot: ${report.player_info.dominant_foot}
Assessment Date: ${report.player_info.assessment_date}

PERFORMANCE SCORES:
Overall Score: ${report.scores.overall_score}/5 (${report.scores.performance_level})
Physical: ${report.scores.physical_score}/5
Technical: ${report.scores.technical_score}/5
Tactical: ${report.scores.tactical_score}/5
Psychological: ${report.scores.psychological_score}/5

AI PERFORMANCE ANALYSIS:
${report.ai_analysis}

COACH RECOMMENDATIONS:
${report.coach_recommendations.map((rec, idx) => `${idx + 1}. ${rec}`).join('\n')}

STANDARDS COMPARISON:
${report.standards_comparison?.analysis || 'See report for details'}

12-WEEK DEVELOPMENT ROADMAP:
Phase 1 (Weeks 1-4): ${report.development_roadmap.phase_1}
Phase 2 (Weeks 5-8): ${report.development_roadmap.phase_2}
Phase 3 (Weeks 9-12): ${report.development_roadmap.phase_3}

Generated by Yo-Yo Elite Soccer Player AI Coach
Report ID: ${report.id}
    `;

    const blob = new Blob([reportText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `assessment-report-${report.player_info.name}-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleGenerateTrainingProgram = async () => {
    try {
      setGeneratingProgram(true);
      const token = localStorage.getItem('token');
      const headers = { Authorization: `Bearer ${token}` };

      // Call AI-powered dynamic program generation
      const response = await axios.post(
        `${BACKEND_URL}/api/training/generate-dynamic-program`,
        {
          // Player basic info
          player_id: user.id,
          player_name: report.player_info.name,
          age: report.player_info.age,
          position: report.player_info.position,
          gender: programParams.gender,
          
          // Assessment results
          assessment_data: report.assessment_data,
          assessment_scores: report.scores,
          performance_level: report.scores.performance_level,
          
          // AI & Coach feedback
          ai_analysis: report.ai_analysis,
          coach_recommendations: report.coach_recommendations,
          standards_comparison: report.standards_comparison,
          
          // Training parameters
          training_days_per_week: programParams.training_days_per_week,
          duration_weeks: programParams.duration_weeks,
          session_duration_minutes: programParams.session_duration_minutes,
          
          // Recovery & injury considerations
          has_injuries: programParams.has_injuries,
          injury_details: programParams.injury_details,
          recovery_priority: programParams.recovery_priority,
          
          // Availability & equipment
          availability: programParams.availability,
          equipment_available: programParams.equipment_available,
          
          // Player goals
          player_goals: programParams.goals
        },
        { headers }
      );

      console.log('Dynamic training program generated:', response.data);
      setProgramGenerated(true);
      setGeneratingProgram(false);
      setShowProgramForm(false);
      
      // Show success message
      alert(`✅ Personalized ${programParams.duration_weeks}-week training program generated!\n\n${programParams.training_days_per_week} sessions per week\nTailored to your assessment results and recovery needs`);
      
    } catch (error) {
      console.error('Error generating training program:', error);
      alert('Error generating training program. Please try again.');
      setGeneratingProgram(false);
    }
  };

  const handleGoToTraining = () => {
    // Close this window and navigate parent to training
    if (window.opener) {
      window.opener.postMessage({ action: 'navigate', tab: 'plan' }, '*');
      window.close();
    } else {
      navigate('/player?tab=plan');
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-16 w-16 border-b-2 border-blue-600 mx-auto mb-4"></div>
          <p className="text-gray-600 text-lg">Generating your professional report...</p>
        </div>
      </div>
    );
  }

  if (!report) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <p className="text-gray-600 text-lg">Report not found</p>
        </div>
      </div>
    );
  }

  const radarData = [
    { category: 'Physical', value: report.scores.physical_score * 20 },
    { category: 'Technical', value: report.scores.technical_score * 20 },
    { category: 'Tactical', value: report.scores.tactical_score * 20 },
    { category: 'Psychological', value: report.scores.psychological_score * 20 }
  ];

  return (
    <div className="min-h-screen bg-gray-50 py-8">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header with Actions */}
        <div className="bg-gradient-to-r from-blue-600 to-blue-800 rounded-2xl p-8 text-white shadow-xl mb-8 print:shadow-none">
          <div className="flex items-center justify-between mb-6">
            <div>
              <h1 className="text-4xl font-bold mb-2">Professional Assessment Report</h1>
              <p className="text-blue-100">AI-Powered Performance Analysis & Development Roadmap</p>
            </div>
            <div className="flex gap-2 print:hidden">
              <button
                onClick={handlePrint}
                className="px-4 py-2 bg-white/20 hover:bg-white/30 rounded-lg transition flex items-center gap-2"
              >
                <Printer className="w-4 h-4" />
                <span>Print</span>
              </button>
              <button
                onClick={handleDownload}
                className="px-4 py-2 bg-white/20 hover:bg-white/30 rounded-lg transition flex items-center gap-2"
              >
                <Download className="w-4 h-4" />
                <span>Download</span>
              </button>
            </div>
          </div>

          {/* Player Info Banner */}
          <div className="bg-white/10 rounded-xl p-6 backdrop-blur-sm">
            <div className="grid grid-cols-2 md:grid-cols-6 gap-4 text-center">
              <div>
                <p className="text-xs text-blue-200 mb-1">Player</p>
                <p className="text-lg font-bold">{report.player_info.name}</p>
              </div>
              <div>
                <p className="text-xs text-blue-200 mb-1">Age</p>
                <p className="text-lg font-bold">{report.player_info.age}</p>
              </div>
              <div>
                <p className="text-xs text-blue-200 mb-1">Position</p>
                <p className="text-lg font-bold">{report.player_info.position}</p>
              </div>
              <div>
                <p className="text-xs text-blue-200 mb-1">Height</p>
                <p className="text-lg font-bold">{report.player_info.height}</p>
              </div>
              <div>
                <p className="text-xs text-blue-200 mb-1">Weight</p>
                <p className="text-lg font-bold">{report.player_info.weight}</p>
              </div>
              <div>
                <p className="text-xs text-blue-200 mb-1">Dominant Foot</p>
                <p className="text-lg font-bold">{report.player_info.dominant_foot}</p>
              </div>
            </div>
          </div>
        </div>

        {/* Overall Score Section */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-8">
          <div className="bg-white rounded-2xl p-8 shadow-lg text-center">
            <div className="w-32 h-32 bg-gradient-to-br from-blue-600 to-blue-800 rounded-full mx-auto mb-4 flex items-center justify-center">
              <span className="text-5xl font-bold text-white">
                {Math.round(report.scores.overall_score * 20)}
              </span>
            </div>
            <h3 className="text-2xl font-bold text-gray-900 mb-2">Overall Score</h3>
            <p className="text-xl text-blue-600 font-semibold">{report.scores.performance_level}</p>
            <p className="text-sm text-gray-500 mt-2">Assessment Date: {report.player_info.assessment_date}</p>
          </div>

          <div className="lg:col-span-2 bg-white rounded-2xl p-6 shadow-lg">
            <h3 className="text-xl font-bold text-gray-900 mb-4">Performance Profile</h3>
            <ResponsiveContainer width="100%" height={300}>
              <RadarChart data={radarData}>
                <PolarGrid stroke="#e5e7eb" />
                <PolarAngleAxis dataKey="category" />
                <PolarRadiusAxis domain={[0, 100]} />
                <Radar name="Performance" dataKey="value" stroke="#2563eb" fill="#2563eb" fillOpacity={0.6} />
              </RadarChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Detailed Scores */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">
          <div className="bg-gradient-to-br from-purple-50 to-purple-100 rounded-xl p-6 text-center shadow">
            <p className="text-sm text-purple-600 font-medium mb-2">Physical</p>
            <p className="text-4xl font-bold text-purple-900">{Math.round(report.scores.physical_score * 20)}</p>
            <p className="text-xs text-purple-600 mt-1">/100</p>
          </div>
          <div className="bg-gradient-to-br from-blue-50 to-blue-100 rounded-xl p-6 text-center shadow">
            <p className="text-sm text-blue-600 font-medium mb-2">Technical</p>
            <p className="text-4xl font-bold text-blue-900">{Math.round(report.scores.technical_score * 20)}</p>
            <p className="text-xs text-blue-600 mt-1">/100</p>
          </div>
          <div className="bg-gradient-to-br from-green-50 to-green-100 rounded-xl p-6 text-center shadow">
            <p className="text-sm text-green-600 font-medium mb-2">Tactical</p>
            <p className="text-4xl font-bold text-green-900">{Math.round(report.scores.tactical_score * 20)}</p>
            <p className="text-xs text-green-600 mt-1">/100</p>
          </div>
          <div className="bg-gradient-to-br from-orange-50 to-orange-100 rounded-xl p-6 text-center shadow">
            <p className="text-sm text-orange-600 font-medium mb-2">Mental</p>
            <p className="text-4xl font-bold text-orange-900">{Math.round(report.scores.psychological_score * 20)}</p>
            <p className="text-xs text-orange-600 mt-1">/100</p>
          </div>
        </div>

        {/* AI Analysis */}
        <div className="bg-white rounded-2xl p-8 shadow-lg mb-8">
          <div className="flex items-center gap-3 mb-6">
            <div className="w-12 h-12 bg-blue-600 rounded-lg flex items-center justify-center">
              <svg className="w-7 h-7 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
              </svg>
            </div>
            <h2 className="text-2xl font-bold text-gray-900">AI Performance Analysis</h2>
          </div>
          <div className="bg-blue-50 rounded-xl p-6">
            <p className="text-gray-800 leading-relaxed whitespace-pre-wrap">{report.ai_analysis}</p>
          </div>
        </div>

        {/* Coach Recommendations */}
        {report.coach_recommendations && report.coach_recommendations.length > 0 && (
          <div className="bg-white rounded-2xl p-8 shadow-lg mb-8">
            <div className="flex items-center gap-3 mb-6">
              <div className="w-12 h-12 bg-green-600 rounded-lg flex items-center justify-center">
                <TrendingUp className="w-7 h-7 text-white" />
              </div>
              <h2 className="text-2xl font-bold text-gray-900">Coach Recommendations</h2>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {report.coach_recommendations.map((rec, idx) => (
                <div key={idx} className="bg-gradient-to-r from-green-50 to-emerald-50 rounded-xl p-5 shadow border border-green-200">
                  <div className="flex items-start gap-3">
                    <div className="w-10 h-10 bg-green-600 text-white rounded-full flex items-center justify-center font-bold flex-shrink-0">
                      {idx + 1}
                    </div>
                    <p className="text-gray-800 font-medium">{rec.replace(/^\d+\.\s*/, '')}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* 12-Week Development Roadmap */}
        <div className="bg-white rounded-2xl p-8 shadow-lg mb-8">
          <h2 className="text-2xl font-bold text-gray-900 mb-6">12-Week Development Roadmap</h2>
          <div className="space-y-4">
            <div className="bg-gradient-to-r from-blue-50 to-indigo-50 rounded-xl p-6 border-l-4 border-blue-600">
              <h3 className="text-lg font-bold text-blue-900 mb-2">Phase 1: Weeks 1-4</h3>
              <p className="text-gray-700">{report.development_roadmap.phase_1}</p>
            </div>
            <div className="bg-gradient-to-r from-purple-50 to-pink-50 rounded-xl p-6 border-l-4 border-purple-600">
              <h3 className="text-lg font-bold text-purple-900 mb-2">Phase 2: Weeks 5-8</h3>
              <p className="text-gray-700">{report.development_roadmap.phase_2}</p>
            </div>
            <div className="bg-gradient-to-r from-green-50 to-teal-50 rounded-xl p-6 border-l-4 border-green-600">
              <h3 className="text-lg font-bold text-green-900 mb-2">Phase 3: Weeks 9-12</h3>
              <p className="text-gray-700">{report.development_roadmap.phase_3}</p>
            </div>
          </div>
        </div>

        {/* Standards Comparison */}
        {report.standards_comparison && (
          <div className="bg-white rounded-2xl p-8 shadow-lg mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-6">Standards Comparison</h2>
            <div className="bg-orange-50 rounded-xl p-6">
              <p className="text-gray-800 leading-relaxed whitespace-pre-wrap">
                {report.standards_comparison.analysis || JSON.stringify(report.standards_comparison, null, 2)}
              </p>
            </div>
          </div>
        )}

        {/* Action Section */}
        <div className="bg-gradient-to-r from-green-600 to-emerald-700 rounded-2xl p-8 text-white shadow-xl print:hidden">
          <h2 className="text-3xl font-bold mb-4">Next Steps: Generate Your Training Program</h2>
          <p className="text-green-100 mb-6 text-lg">
            Based on this comprehensive assessment, we can now create your personalized 12-week training program. 
            This program will be specifically designed to improve your identified areas while maintaining your strengths.
          </p>
          
          <div className="flex gap-4">
            {!programGenerated ? (
              <button
                onClick={() => setShowProgramForm(true)}
                disabled={generatingProgram}
                className="px-8 py-4 bg-white text-green-700 rounded-xl font-bold text-lg hover:bg-green-50 transition shadow-lg disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-3"
              >
                {generatingProgram ? (
                  <>
                    <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-green-700"></div>
                    Generating AI-Powered Program...
                  </>
                ) : (
                  <>
                    <Play className="w-6 h-6" />
                    Generate Personalized Program
                  </>
                )}
              </button>
            ) : (
              <button
                onClick={handleGoToTraining}
                className="px-8 py-4 bg-white text-green-700 rounded-xl font-bold text-lg hover:bg-green-50 transition shadow-lg flex items-center gap-3"
              >
                <CheckCircle className="w-6 h-6" />
                Go to Training Plan
                <ArrowRight className="w-6 h-6" />
              </button>
            )}
          </div>

          {programGenerated && (
            <div className="mt-4 bg-white/20 rounded-lg p-4 backdrop-blur-sm">
              <p className="text-sm">
                ✅ Your personalized training program has been generated! You can now view it in your Training Plan section 
                where you'll be able to track your progress, mark completed sessions, and see your improvement over time.
              </p>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="text-center py-8 text-gray-500 text-sm print:block">
          <p>Report Generated: {new Date(report.generated_at).toLocaleString()}</p>
          <p className="mt-2">Yo-Yo Elite Soccer Player AI Coach • Report ID: {report.id}</p>
        </div>
      </div>

      {/* Program Parameters Modal */}
      {showProgramForm && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-2xl max-w-3xl w-full max-h-[90vh] overflow-y-auto shadow-2xl">
            <div className="bg-gradient-to-r from-blue-600 to-blue-800 p-6 text-white rounded-t-2xl">
              <h2 className="text-2xl font-bold mb-2">Customize Your Training Program</h2>
              <p className="text-blue-100">AI will generate a personalized program based on these parameters</p>
            </div>

            <div className="p-6 space-y-6">
              {/* Training Schedule */}
              <div>
                <h3 className="text-lg font-bold text-gray-900 mb-4">Training Schedule</h3>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      Days per Week *
                    </label>
                    <select
                      value={programParams.training_days_per_week}
                      onChange={(e) => setProgramParams({...programParams, training_days_per_week: parseInt(e.target.value)})}
                      className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
                    >
                      <option value="2">2 days (Light)</option>
                      <option value="3">3 days (Moderate)</option>
                      <option value="4">4 days (Regular)</option>
                      <option value="5">5 days (Intensive)</option>
                      <option value="6">6 days (Elite)</option>
                      <option value="7">7 days (Professional)</option>
                    </select>
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      Program Duration *
                    </label>
                    <select
                      value={programParams.duration_weeks}
                      onChange={(e) => setProgramParams({...programParams, duration_weeks: parseInt(e.target.value)})}
                      className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
                    >
                      <option value="4">4 weeks (Short-term)</option>
                      <option value="6">6 weeks (Standard)</option>
                      <option value="8">8 weeks (Extended)</option>
                      <option value="12">12 weeks (Full cycle)</option>
                      <option value="16">16 weeks (Season prep)</option>
                      <option value="24">24 weeks (Full season)</option>
                    </select>
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      Session Duration
                    </label>
                    <select
                      value={programParams.session_duration_minutes}
                      onChange={(e) => setProgramParams({...programParams, session_duration_minutes: parseInt(e.target.value)})}
                      className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
                    >
                      <option value="30">30 minutes</option>
                      <option value="45">45 minutes</option>
                      <option value="60">60 minutes</option>
                      <option value="75">75 minutes</option>
                      <option value="90">90 minutes</option>
                      <option value="120">120 minutes</option>
                    </select>
                  </div>
                </div>
              </div>

              {/* Personal Info */}
              <div>
                <h3 className="text-lg font-bold text-gray-900 mb-4">Personal Information</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      Gender
                    </label>
                    <select
                      value={programParams.gender}
                      onChange={(e) => setProgramParams({...programParams, gender: e.target.value})}
                      className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
                    >
                      <option value="male">Male</option>
                      <option value="female">Female</option>
                      <option value="other">Other</option>
                    </select>
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      Availability
                    </label>
                    <select
                      value={programParams.availability}
                      onChange={(e) => setProgramParams({...programParams, availability: e.target.value})}
                      className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
                    >
                      <option value="morning">Morning (6-9 AM)</option>
                      <option value="after_school">After School (3-6 PM)</option>
                      <option value="evening">Evening (6-9 PM)</option>
                      <option value="flexible">Flexible</option>
                    </select>
                  </div>
                </div>
              </div>

              {/* Injury & Recovery */}
              <div>
                <h3 className="text-lg font-bold text-gray-900 mb-4">Injury & Recovery</h3>
                <div className="space-y-4">
                  <div>
                    <label className="flex items-center gap-2">
                      <input
                        type="checkbox"
                        checked={programParams.has_injuries}
                        onChange={(e) => setProgramParams({...programParams, has_injuries: e.target.checked})}
                        className="w-4 h-4 text-blue-600 rounded focus:ring-2 focus:ring-blue-500"
                      />
                      <span className="text-sm font-medium text-gray-700">I have current injuries or concerns</span>
                    </label>
                  </div>
                  {programParams.has_injuries && (
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-2">
                        Injury Details
                      </label>
                      <textarea
                        value={programParams.injury_details}
                        onChange={(e) => setProgramParams({...programParams, injury_details: e.target.value})}
                        placeholder="Describe any injuries, pain, or areas to avoid..."
                        className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
                        rows="3"
                      />
                    </div>
                  )}
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      Recovery Priority
                    </label>
                    <select
                      value={programParams.recovery_priority}
                      onChange={(e) => setProgramParams({...programParams, recovery_priority: e.target.value})}
                      className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
                    >
                      <option value="low">Low (Push hard)</option>
                      <option value="moderate">Moderate (Balanced)</option>
                      <option value="high">High (Extra rest days)</option>
                      <option value="injury_prevention">Injury Prevention Focus</option>
                    </select>
                  </div>
                </div>
              </div>

              {/* Equipment & Goals */}
              <div>
                <h3 className="text-lg font-bold text-gray-900 mb-4">Equipment & Goals</h3>
                <div className="space-y-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      Equipment Available
                    </label>
                    <select
                      value={programParams.equipment_available}
                      onChange={(e) => setProgramParams({...programParams, equipment_available: e.target.value})}
                      className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
                    >
                      <option value="minimal">Minimal (Just a ball)</option>
                      <option value="basic">Basic (Ball, cones, small space)</option>
                      <option value="full">Full (Field, goals, full equipment)</option>
                      <option value="gym">Gym Access</option>
                    </select>
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      Your Goals (Optional)
                    </label>
                    <textarea
                      value={programParams.goals}
                      onChange={(e) => setProgramParams({...programParams, goals: e.target.value})}
                      placeholder="E.g., Make the varsity team, improve speed, better first touch..."
                      className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
                      rows="3"
                    />
                  </div>
                </div>
              </div>

              {/* AI Notice */}
              <div className="bg-blue-50 rounded-xl p-4 border border-blue-200">
                <div className="flex items-start gap-3">
                  <svg className="w-6 h-6 text-blue-600 flex-shrink-0 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                  </svg>
                  <div>
                    <p className="text-sm font-medium text-blue-900 mb-1">AI-Powered Personalization</p>
                    <p className="text-xs text-blue-700">
                      Our AI will analyze your assessment results ({report.scores.performance_level} level), 
                      age ({report.player_info.age}), position ({report.player_info.position}), and all parameters above to create 
                      a perfectly tailored {programParams.duration_weeks}-week program with {programParams.training_days_per_week} sessions per week.
                    </p>
                  </div>
                </div>
              </div>

              {/* Action Buttons */}
              <div className="flex gap-4 pt-4">
                <button
                  onClick={handleGenerateTrainingProgram}
                  disabled={generatingProgram}
                  className="flex-1 px-6 py-3 bg-gradient-to-r from-blue-600 to-blue-800 text-white rounded-xl font-bold hover:from-blue-700 hover:to-blue-900 transition disabled:opacity-50"
                >
                  {generatingProgram ? 'Generating...' : 'Generate Program with AI'}
                </button>
                <button
                  onClick={() => setShowProgramForm(false)}
                  disabled={generatingProgram}
                  className="px-6 py-3 bg-gray-200 text-gray-700 rounded-xl font-semibold hover:bg-gray-300 transition"
                >
                  Cancel
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default ProfessionalAssessmentReport;
